# Generated by Django 4.2.29 on 2026-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer')], default='customer', help_text='Authorization role. Super Admin > Admin > Vendor > Customer.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin_user',
            field=models.BooleanField(default=False, help_text='Legacy flag, superseded by `role`. Kept so existing data is not lost.'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='accounts_us_role_e16858_idx'),
        ),
    ]
