# Generated by Django 4.2.29 on 2026-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_missing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_version',
            field=models.PositiveIntegerField(default=0, help_text='Bump to revoke every token issued to this user so far.'),
        ),
    ]
