# Generated by Django 4.2.29 on 2026-04-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('festival_type', models.CharField(choices=[('dashain', 'Dashain'), ('tihar', 'Tihar'), ('shivaratri', 'Maha Shivaratri'), ('bratabandha', 'Bratabandha'), ('pasni', 'Pasni (Rice Feeding)'), ('griha_pravesh', 'Griha Pravesh'), ('shraddha', 'Shraddha'), ('teej', 'Teej'), ('chhath', 'Chhath Puja'), ('saraswati', 'Saraswati Puja'), ('nag_panchami', 'Nag Panchami'), ('janai_purnima', 'Janai Purnima'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='kits/')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['festival_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UpcomingFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('festival_type', models.CharField(choices=[('dashain', 'Dashain'), ('tihar', 'Tihar'), ('shivaratri', 'Maha Shivaratri'), ('bratabandha', 'Bratabandha'), ('pasni', 'Pasni (Rice Feeding)'), ('griha_pravesh', 'Griha Pravesh'), ('shraddha', 'Shraddha'), ('teej', 'Teej'), ('chhath', 'Chhath Puja'), ('saraswati', 'Saraswati Puja'), ('nag_panchami', 'Nag Panchami'), ('janai_purnima', 'Janai Purnima'), ('other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='festivals.festivalkit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('kit', 'product')},
            },
        ),
    ]
