# Generated by Django 4.2.29 on 2026-09-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_area_delivery_fee_alter_product_price'),
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('occasion_type', models.CharField(blank=True, choices=[('dashain', 'Dashain'), ('tihar', 'Tihar'), ('shivaratri', 'Maha Shivaratri'), ('bratabandha', 'Bratabandha'), ('pasni', 'Pasni (Rice Feeding)'), ('griha_pravesh', 'Griha Pravesh'), ('shraddha', 'Shraddha'), ('teej', 'Teej'), ('chhath', 'Chhath Puja'), ('saraswati', 'Saraswati Puja'), ('nag_panchami', 'Nag Panchami'), ('janai_purnima', 'Janai Purnima'), ('other', 'Other')], help_text='Optional link to the same vocabulary kits and the calendar use.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pujas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='festivalkit',
            name='puja',
            field=models.ForeignKey(blank=True, help_text='The ritual this kit is assembled for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits', to='festivals.puja'),
        ),
        migrations.CreateModel(
            name='PujaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('puja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='festivals.puja')),
            ],
            options={
                'ordering': ['-is_required', 'id'],
                'unique_together': {('puja', 'product')},
            },
        ),
    ]
