# Generated by Django 4.2.29 on 2026-09-19 11:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_seed_areas_and_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override the store-wide delivery fee for this area. Blank = use the default.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
