# Generated by Django 4.2.29 on 2026-09-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('festival_context', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_sales', to='products.product')),
            ],
            options={
                'ordering': ['product_id', 'date'],
                'indexes': [models.Index(fields=['product', 'date'], name='analytics_s_product_4d35c1_idx'), models.Index(fields=['date'], name='analytics_s_date_c8147f_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
