"""Analytics models.

This app previously had no models at all — it was pure aggregation over the
orders tables. The one model added here exists solely to hold the **synthetic**
sales history used by the demand-forecasting pipeline.

Why a separate table instead of reusing ``orders``:

* Real orders must never be polluted with fabricated rows. Mixing them would make
  the admin dashboard lie about revenue.
* The ``is_synthetic`` flag is stored per row and asserted in every API response,
  so the provenance of the data is impossible to lose track of.
* Deleting the whole synthetic dataset is one query, and it cannot touch a real
  order.

If real sales volume ever becomes sufficient, the forecaster can be pointed at
``OrderItem`` aggregates instead and this table can be dropped — the forecasting
code itself needs no change.
"""

from django.db import models


class SyntheticSalesRecord(models.Model):
    """A single day of *fabricated* sales demand for one product.

    **This is not real data.** See ``analytics/forecasting.py`` for how it is
    generated and ``docs/AI-PREDICTION.md`` for why it exists.

    Rows are generated by ``python manage.py generate_synthetic_sales``.
    """

    product = models.ForeignKey(
        'products.Product', on_delete=models.CASCADE, related_name='synthetic_sales',
    )
    date = models.DateField()
    units_sold = models.PositiveIntegerField(default=0)

    # Provenance. Always True for rows in this table; the field exists so the
    # invariant is explicit and queryable rather than implied by the table name.
    is_synthetic = models.BooleanField(default=True)

    # Which festival was driving this day's demand, if any. Useful for auditing
    # that the generated seasonality actually landed where intended.
    festival_context = models.CharField(max_length=30, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['product_id', 'date']
        # One row per product per day.
        unique_together = ('product', 'date')
        indexes = [
            models.Index(fields=['product', 'date']),
            models.Index(fields=['date']),
        ]

    def __str__(self):
        tag = 'SYNTHETIC' if self.is_synthetic else 'REAL'
        return f'[{tag}] {self.product_id} {self.date} = {self.units_sold}u'
